[book]
src = "src"
title = "Euler Swap Contracts Documentation"

[output.html]
no-section-label = true
additional-js = ["solidity.min.js"]
additional-css = ["book.css"]
git-repository-url = "https://github.com/euler-xyz/euler-maglev"

[output.html.fold]
enable = true
